version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: credit-jambo-client-postgres
    environment:
      POSTGRES_DB: credit_jambo_client
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - credit-jambo-client

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: credit-jambo-client-backend
    env_file:
      - ./backend/.env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit-jambo-client
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  credit-jambo-client:
    driver: bridge
